from playwright.sync_api import Page,expect
from datetime import datetime, timedelta
current_time=datetime.now().strftime("%m/%d/%Y")
future_date=datetime.now()+timedelta(days=7)
print(current_time)
print(future_date.strftime("%m/%d/%Y"))
def test_dates(page:Page):
    page.goto("https://testautomationpractice.blogspot.com/")
    page.evaluate("window.scrollBy(0,1000)")
    page.wait_for_timeout(4000)
    page.get_by_placeholder("Start Date").click()
    page.wait_for_timeout(4000)
    #page.get_by_placeholder('Start Date').fill('2026')
    page.keyboard.type('2026')
    page.wait_for_timeout(4000)
    #page.keyboard.press('ArrowLeft')
    page.keyboard.press('Shift+Tab')
    #page.get_by_placeholder('Start Date').fill(6)
    page.keyboard.type('6')
    page.wait_for_timeout(4000)
    #page.keyboard.press('ArrowLeft')
    #page.get_by_placeholder('Start Date').fill(29)
    page.keyboard.press('Shift+Tab')
    page.keyboard.press('Shift+Tab')
    page.keyboard.type('29')
    page.wait_for_timeout(4000)
    page.keyboard.press('Enter')
    page.get_by_placeholder("End Date").click()
    page.keyboard.type('2026')
    #page.keyboard.press('ArrowLeft')
    page.keyboard.press('Shift+Tab')
    #page.get_by_placeholder("End Date").fill(7)
    page.keyboard.type('7')
    #page.keyboard.press('ArrowLeft')
    page.keyboard.press('Shift+Tab')
    page.keyboard.press('Shift+Tab')
    #page.get_by_placeholder("End Date").fill(7)
    page.keyboard.type('7')
    page.keyboard.press('Enter')
    page.wait_for_timeout(4000)
    page.locator('[class="submit-btn"]').click()
    #print(sub)
    page.wait_for_timeout(5000)

